name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      - name: Install dependencies
        run: |
          uv export --no-hashes | uv pip install -r - basedpyright
      - name: Lint with Ruff
        run: |
          ruff check --output-format github
          ruff format --check --diff
      - name: Type check with Pyright
        run: |
          basedpyright
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
